name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Simulate deployment
        run: |
          echo "Deploying application..."
          echo "Deployment complete ✅" > deploy.log

      - name: Display deployment log
        run: cat deploy.log

      - name: Upload deployment log
        uses: actions/upload-artifact@v3
        with:
          name: deployment-log
          path: deploy.log
      - name: Notify deployment success
        run: |
          echo "Deployment was successful! 🎉"
          # Here you could add a step to notify a service like Slack, Discord, etc.
          # For example:
          # curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment was successful!"}' YOUR_WEBHOOK_URL