name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI Demo"]
    types: [completed]

jobs:
  celebrate:
    runs-on: ubuntu-latest
    steps:
      - name: Print completion
        run: |
          echo "🎉 CD triggered because CI finished!"
          echo "This would deploy your app in real projects"
          echo "Workflow result: ${{ github.event.workflow_run.conclusion }}"