name: CD - Main

on:
  workflow_run:
    workflows: ["CI - Main"]
    types: [completed]

jobs:
  deploy-main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Simulate deployment for main
        run: |
          echo "Deploying MAIN branch..."
          echo "✅ Main deployment complete!" > deploy-main.log

      - name: Show deployment log
        run: cat deploy-main.log

