name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continous Integration"]
    # This workflow will run when the CI workflow is completed
    # The workflow_run event is triggered when a workflow run is completed
    types: [completed]

jobs:
  celebrate:
    runs-on: ubuntu-latest
    steps:
      - name: Print completion
        run: |
          echo "🎉 CD triggered because CI finished!" (Job Done!)
          echo "This would deploy your app in real projects"
          echo "Workflow result: ${{ github.event.workflow_run.conclusion }}"