name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Verify deployment files
        run: |
          [ -f deploy.sh ] || { echo "Missing deploy.sh"; exit 1; }
          [ -f config.yaml ] || { echo "Missing config.yaml"; exit 1; }

      - name: Generate deployment log
        run: echo "CD passed ✅" > cd-success.txt

      - name: Upload deployment log
        uses: actions/upload-artifact@v3.1.3
        with:
          name: cd-success
          path: cd-success.txt

      - name: Simulate deployment
        run: |
          echo "Simulating deployment..."
          echo "Deploying branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Deployment complete ✅" > deploy.log

      - name: Display deployment log
        run: cat deploy.log

      - name: Upload deployment log
        uses: actions/upload-artifact@v3.1.3
        with:
          name: deployment-log
          path: deploy.log
