name: Continuous Integration

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [main]

jobs:
  run-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Print CI message
        run: echo "✅ CI is working on ${{ github.ref_name }} branch!"
