name: Continous Integration 

on: [push]  # Runs on any push

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "✅ CI is working Fine! (This ran because you pushed code)"
        
      - name: Count files
        run: |
          echo "This repo has $(find . -type f | wc -l) files"
          echo "Files list:" >> file-report.txt
          find . -type f >> file-report.txt
          
      - name: Save report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ci-report
          path: file-report.txt