name: CI - Feature Login

on:
  push:
    branches: [feature/login]
  pull_request:
    branches: [main]

jobs:
  validate-feature:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Check login files
        run: |
          [ -f login.html ] || { echo "Missing login.html"; exit 1; }
          [ -f login.css ] || { echo "Missing login.css"; exit 1; }

      - name: Success message
        run: echo "CI for feature/login passed ✅"
