name: Continuous Integration

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify required files exist
        run: |
          [ -f index.html ] || { echo "Missing index.html"; exit 1; }
          [ -f style.css ] || { echo "Missing style.css"; exit 1; }

      - name: Generate success file
        run: echo "CI passed ✅" > ci-success.txt

      - name: Upload success flag
        uses: actions/upload-artifact@v3
        with:
          name: ci-success
          path: ci-success.txt
      