name: Feature CI (Login)

on:
  push:
    branches: [feature/login]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI is working on feature/login"