name: Feature CI (Login)

on:
  push:
    branches: [feature/login]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print a message
        run: |
          echo "✅ This is CI on feature/login."
          echo "Branch: ${{ github.ref_name }}"
