name: Hello World
on:
    workflow_dispatch:

jobs:
    print-hello-world:
        runs-on: ubuntu-22.04
        steps:
            - name: Print Hello World
              run: echo "Hello, World!"
            