name: Hello Today Workflow

on:
    workflow_dispatch:

jobs:
    print-hello-world:
        runs-on: ubuntu-22.04
        steps:
            - name: Print Hello Today Test
              run: echo "Hello, Today!"
            