name: Simple CD

on:
  workflow_run:
    workflows: ["Simple CD"]
    types: [completed]

jobs:
  run-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Simulate deployment
        run: |
          echo "✅ Deployment complete Succesful!"
          